source 'http://tfs.teld.cn:8080/tfs/teld/APP/_git/iOS_TLDSpecs'
source 'https://github.com/CocoaPods/Specs.git'
target 'YTKNetworkDemo' do
    pod 'TLDNetwork', :path => '../'
end

target 'YTKNetworkDemoTests' do
    pod 'TLDNetwork',:path => '../'
end

